config/routes.rb
Myapp::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root to: 'userhome#personal'

  # All routes
  get "userhome/index"
  get "userhome/education"
  get "userhome/experience"
  get "userhome/hobbies"
  get "userhome/languages"
  get "userhome/personal"
  get "userhome/volunteering"

  get "companyhome/index"
  get "companyhome/companydata"
  get "companyhome/contacts"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/datamaps"
  get "miscellaneous/social_buttons"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/pdf_viewer"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/helper_classes"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "cssanimations/index"

  get "landing/index"

end

app/controllers/companyhome_controller.rb
class CompanyhomeController < ApplicationController
  def companydata
  end

  def contacts
  end

end

app/controllers/userhome_controller.rb
class UserhomeController < ApplicationController
  def personal
  end

  def advanced
  end

  def wizard
  end

  def file_upload
  end

  def text_editor
  end

  def markdown
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/views/companyhome/education.html.erb
<!-- vim: noai:ts=4:sw=4:nu
-->

<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-10">
		<h2>Datos Personales</h2>
			<ol class="breadcrumb">
			<li>
				<a href="<%= url_for :controller => 'userhome', :action => 'personal' %>">Home</a>
			</li>
			<li>
				<a>userHome</a>
			</li>
			<li class="active">
				<strong>Educacion Reglada</strong>
			</li>
		</ol>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">

		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title  back-change">
					<h5>Formacion Recibida</h5>
				</div>
				<div class="ibox-content">
					<div class="row">
					<form method="get" class="form-horizontal">	
						<div class="col-md-6 form-group">
							<div class="form-group"><label class="col-sm-2 control-label">Titulo</label>
								<div class="col-sm-10"><input type="text" class="form-control"></div>
							</div>
							<div class="col-sm-12 form-group" id="data_1">
								<div class="col-sm-12 input-group date">
									<span class="input-group-addon">Inicio <i class="fa fa-calendar"></i></span>
									<input type="text" class="form-control" value="28/12/2015">
								</div>
								<div class="col-sm-12 input-group date">
									<span class="input-group-addon">Final&nbsp; <i class="fa fa-calendar"></i></span>
									<input type="text" class="form-control" value="28/12/2016">
								</div>
							</div>
						</div>
						<div class="col-md-6">	
							<div class="form-group"><label class="col-sm-2 control-label">Nombre centro</label>
								<div class="col-sm-10"><input type="text" class="form-control"></div>
							</div>
							<div class="form-group"><label class="col-sm-2 control-label">Tipo</label>
								<div class="col-sm-10"><input type="text" class="form-control"></div>
							</div>
						</div>
						<div class="col-md-12 form-group">
							<div class="summernote">
								<h3>Explicacion de prueba</h3>
								Trabajo para <strong>UniON</strong>. Y cada dia soy mas feliz.
								<ul>
								<li>Prueba apartado 1</li>
								<li>Prueba apartado 2</li>
								</ul>
							</div>
						</div>
					</form>
					</div>
				</div>
			</div>
		</div>

	</div> <!-- el cierre del row -->

</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    // $('.summernote').summernote();

$('.summernote').summernote({
  toolbar: [
    // [groupName, [list of button]]
    ['type', ['style']],
    ['style', ['bold', 'italic', 'underline', 'clear']],
    ['para', ['ul', 'ol', 'paragraph']],
  ]
});

    var edit = function () {
        $('.click2edit').summernote({ focus: true });
    };

    $("#edit").click(function () {
        $('.click2edit').summernote({ focus: true });
    });

    $("#save").click(function () {
        var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
        $('.click2edit').destroy();
    });

var $image = $(".image-crop > img")
$($image).cropper({
aspectRatio: 1.618,
preview: ".img-preview",
done: function (data) {
// Output the result data for cropping image.
}
});

var $inputImage = $("#inputImage");
if (window.FileReader) {
$inputImage.change(function () {
var fileReader = new FileReader(),
files = this.files,
file;

if (!files.length) {
return;
}

file = files[0];

if (/^image\/\w+$/.test(file.type)) {
fileReader.readAsDataURL(file);
fileReader.onload = function () {
$inputImage.val("");
$image.cropper("reset", true).cropper("replace", this.result);
};
} else {
showMessage("Please choose an image file.");
}
});
} else {
$inputImage.addClass("hide");
}

$("#download").click(function () {
window.open($image.cropper("getDataURL"));
});

$("#zoomIn").click(function () {
$image.cropper("zoom", 0.1);
});

$("#zoomOut").click(function () {
$image.cropper("zoom", -0.1);
});

$("#rotateLeft").click(function () {
$image.cropper("rotate", 45);
});

$("#rotateRight").click(function () {
$image.cropper("rotate", -45);
});

$("#setDrag").click(function () {
$image.cropper("setDragMode", "crop");
});

$('#data_1 .input-group.date').datepicker({
todayBtn: "linked",
keyboardNavigation: false,
forceParse: false,
calendarWeeks: true,
autoclose: true
});

$('#data_2 .input-group.date').datepicker({
startView: 1,
todayBtn: "linked",
keyboardNavigation: false,
forceParse: false,
autoclose: true
});

$('#data_3 .input-group.date').datepicker({
startView: 2,
todayBtn: "linked",
keyboardNavigation: false,
forceParse: false,
autoclose: true
});

$('#data_4 .input-group.date').datepicker({
minViewMode: 1,
keyboardNavigation: false,
forceParse: false,
autoclose: true,
todayHighlight: true
});

$('#data_5 .input-daterange').datepicker({
keyboardNavigation: false,
forceParse: false,
autoclose: true
});

var elem = document.querySelector('.js-switch');
var switchery = new Switchery(elem, { color: '#1AB394' });

var elem_2 = document.querySelector('.js-switch_2');
var switchery_2 = new Switchery(elem_2, { color: '#ED5565' });

var elem_3 = document.querySelector('.js-switch_3');
var switchery_3 = new Switchery(elem_3, { color: '#1AB394' });

$('.i-checks').iCheck({
checkboxClass: 'icheckbox_square-green',
radioClass: 'iradio_square-green',
});

$('.demo1').colorpicker();

var divStyle = $('.back-change')[0].style;
$('#demo_apidemo').colorpicker({
color: divStyle.backgroundColor
}).on('changeColor', function (ev) {
divStyle.backgroundColor = ev.color.toHex();
});

$('.chosen-select').chosen({width: "100%"});

$(".select2_demo_1").select2();
$(".select2_demo_2").select2();
$(".select2_demo_3").select2({
placeholder: "Select a state",
allowClear: true
});

$(".touchspin1").TouchSpin({
buttondown_class: 'btn btn-white',
buttonup_class: 'btn btn-white'
});

$(".touchspin2").TouchSpin({
min: 0,
max: 100,
step: 0.1,
decimals: 2,
boostat: 5,
maxboostedstep: 10,
postfix: '%',
buttondown_class: 'btn btn-white',
buttonup_class: 'btn btn-white'
});

$(".touchspin3").TouchSpin({
verticalbuttons: true,
buttondown_class: 'btn btn-white',
buttonup_class: 'btn btn-white'
});

$("#ionrange_1").ionRangeSlider({
min: 0,
max: 5000,
type: 'double',
prefix: "$",
maxPostfix: "+",
prettify: false,
hasGrid: true
});

$("#ionrange_2").ionRangeSlider({
min: 0,
max: 10,
type: 'single',
step: 0.1,
postfix: " carats",
prettify: false,
hasGrid: true
});

$("#ionrange_3").ionRangeSlider({
min: -50,
max: 50,
from: 0,
postfix: "°",
prettify: false,
hasGrid: true
});

$("#ionrange_4").ionRangeSlider({
values: [
"January", "February", "March",
"April", "May", "June",
"July", "August", "September",
"October", "November", "December"
],
type: 'single',
hasGrid: true
});

$("#ionrange_5").ionRangeSlider({
min: 10000,
max: 100000,
step: 100,
postfix: " km",
from: 55000,
hideMinMax: true,
hideFromTo: false
});

$(".dial").knob();

$("#basic_slider").noUiSlider({
start: 40,
behaviour: 'tap',
connect: 'upper',
range: {
'min': 20,
'max': 80
}
});

$("#range_slider").noUiSlider({
start: [40, 60],
behaviour: 'drag',
connect: true,
range: {
'min': 20,
'max': 80
}
});

$("#drag-fixed").noUiSlider({
start: [40, 60],
behaviour: 'drag-fixed',
connect: true,
range: {
'min': 20,
'max': 80
}
});

$('.clockpicker').clockpicker();

$('input[name="daterange"]').daterangepicker();

$('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));

$('#reportrange').daterangepicker({
format: 'MM/DD/YYYY',
startDate: moment().subtract(29, 'days'),
endDate: moment(),
minDate: '01/01/2012',
maxDate: '12/31/2015',
dateLimit: { days: 60 },
showDropdowns: true,
showWeekNumbers: true,
timePicker: false,
timePickerIncrement: 1,
timePicker12Hour: true,
ranges: {
'Today': [moment(), moment()],
'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
'Last 7 Days': [moment().subtract(6, 'days'), moment()],
'Last 30 Days': [moment().subtract(29, 'days'), moment()],
'This Month': [moment().startOf('month'), moment().endOf('month')],
'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
},
opens: 'right',
drops: 'down',
buttonClasses: ['btn', 'btn-sm'],
applyClass: 'btn-primary',
cancelClass: 'btn-default',
separator: ' to ',
locale: {
applyLabel: 'Submit',
cancelLabel: 'Cancel',
fromLabel: 'From',
toLabel: 'To',
customRangeLabel: 'Custom',
daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr','Sa'],
monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
firstDay: 1
}
}, function(start, end, label) {
console.log(start.toISOString(), end.toISOString(), label);
$('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
});


$('.dual_select').bootstrapDualListbox({
selectorMinimalHeight: 160
});

$('.tagsinput').tagsinput({
tagClass: 'label label-primary'
});

});

</script>

<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Unete a nuestra comunidad en facebook: <a href="https://www.facebook.com/Km0formacion/">@Km0formacion</a>
    </div>
    <div>
        <strong>Copyright</strong> UniON &copy; 2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="<%= image_url 'UNION.jpg' %>"/>
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <!-- <strong class="font-bold">Carlos Salamanca</strong> -->
                            <!-- </span> <span class="text-muted text-xs block">IT Director <b class="caret"></b></span> //-->
                        </span>
                    </a>
<!--
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="">Profile</a>
                        </li>
                        <li><a href="">Contacts</a>
                        </li>
                        <li><a href="">Mailbox</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="">Logout</a>
                        </li>
                    </ul>
//-->
                </div>
                <div class="logo-element">
                    KM0
                </div>
            </li>
            <li class="<%= is_active_controller('userhome') %>">
                <a href="#"><i class="fa fa-user"></i> <span class="nav-label" data-i18n="nav.forms">Perfil</span></a>
                <ul class="nav nav-second-level collapse <%= is_active_controller('userhome') %>">
                    <li class="<%= is_active_action('personal') %>"><%= link_to "Personal", userhome_personal_path %></li>
                    <li class="<%= is_active_action('education') %>"><%= link_to "Educacion", userhome_education_path %></li>
                    <li class="<%= is_active_action('experience') %>"><%= link_to "Experiencia", userhome_experience_path %></li>
                    <li class="<%= is_active_action('hobbies') %>"><%= link_to "Hobbies", userhome_hobbies_path %></li>
                    <li class="<%= is_active_action('languages') %>"><%= link_to "Idiomas", userhome_languages_path %></li>
                    <li class="<%= is_active_action('volunteering') %>"><%= link_to "Voluntariado", userhome_volunteering_path %></li>
                </ul>
            </li>
            <li class="<%= is_active_controller('companyhome') %>">
                <a href="#"><i class="fa fa-user"></i> <span class="nav-label" data-i18n="nav.forms">Compañia</span></a>
                <ul class="nav nav-second-level collapse <%= is_active_controller('companyhome') %>">
                    <li class="<%= is_active_action('companydata') %>"><%= link_to "Datos principales", companyhome_companydata_path %></li>
                    <li class="<%= is_active_action('contacts') %>"><%= link_to "Contactos", companyhome_contacts_path %></li>
                </ul>
            </li>
        </ul>

    </div>
</nav>

app/views/layouts/_skinconfig.html.erb
<div class="theme-config">
    <div class="theme-config-box">
        <div class="spin-icon">
            <i class="fa fa-cogs fa-spin"></i>
        </div>
        <div class="skin-setttings">
            <div class="title">Configuration</div>
            <div class="setings-item">
                    <span>
                        Collapse menu
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                        <label class="onoffswitch-label" for="collapsemenu">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Fixed sidebar
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedsidebar" class="onoffswitch-checkbox" id="fixedsidebar">
                        <label class="onoffswitch-label" for="fixedsidebar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Top navbar
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                        <label class="onoffswitch-label" for="fixednavbar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Top navbar v.2
                        <br/>
                        <small>*Primary layout</small>
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar2" class="onoffswitch-checkbox" id="fixednavbar2">
                        <label class="onoffswitch-label" for="fixednavbar2">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Boxed layout
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                        <label class="onoffswitch-label" for="boxedlayout">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Fixed footer
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedfooter" class="onoffswitch-checkbox" id="fixedfooter">
                        <label class="onoffswitch-label" for="fixedfooter">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="title">Skins</div>
            <div class="setings-item default-skin">
                    <span class="skin-name ">
                         <a href="#" class="s-skin-0">
                             Default
                         </a>
                    </span>
            </div>
            <div class="setings-item blue-skin">
                    <span class="skin-name ">
                        <a href="#" class="s-skin-1">
                            Blue light
                        </a>
                    </span>
            </div>
            <div class="setings-item yellow-skin">
                    <span class="skin-name ">
                        <a href="#" class="s-skin-3">
                            Yellow/Purple
                        </a>
                    </span>
            </div>
            <div class="setings-item ultra-skin">
                    <span class="skin-name ">
                        <a target="_blank" href="md_skin/" class="md-skin">
                            Material Design
                        </a>
                    </span>
            </div>
        </div>
    </div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">
// Config box

// Enable/disable fixed top navbar
$('#fixednavbar').click(function (){
    if ($('#fixednavbar').is(':checked')){
        $(".navbar-static-top").removeClass('navbar-static-top').addClass('navbar-fixed-top');
        $("body").removeClass('boxed-layout');
        $("body").addClass('fixed-nav');
        $('#boxedlayout').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'on');
        }
    } else{
        $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
        $("body").removeClass('fixed-nav');
        $("body").removeClass('fixed-nav-basic');
        $('#fixednavbar2').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'off');
        }
    }
});

// Enable/disable fixed top navbar
$('#fixednavbar2').click(function (){
    if ($('#fixednavbar2').is(':checked')){
        $(".navbar-static-top").removeClass('navbar-static-top').addClass('navbar-fixed-top');
        $("body").removeClass('boxed-layout');
        $("body").addClass('fixed-nav').addClass('fixed-nav-basic');
        $('#boxedlayout').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'on');
        }
    } else {
        $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
        $("body").removeClass('fixed-nav').removeClass('fixed-nav-basic');
        $('#fixednavbar').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'off');
        }
        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'off');
        }
    }
});

// Enable/disable fixed sidebar
$('#fixedsidebar').click(function (){
    if ($('#fixedsidebar').is(':checked')){
        $("body").addClass('fixed-sidebar');
        $('.sidebar-collapse').slimScroll({
            height: '100%',
            railOpacity: 0.9
        });

        if (localStorageSupport){
            localStorage.setItem("fixedsidebar",'on');
        }
    } else{
        $('.sidebar-collapse').slimscroll({destroy: true});
        $('.sidebar-collapse').attr('style', '');
        $("body").removeClass('fixed-sidebar');

        if (localStorageSupport){
            localStorage.setItem("fixedsidebar",'off');
        }
    }
});

// Enable/disable collapse menu
$('#collapsemenu').click(function (){
    if ($('#collapsemenu').is(':checked')){
        $("body").addClass('mini-navbar');
        SmoothlyMenu();

        if (localStorageSupport){
            localStorage.setItem("collapse_menu",'on');
        }

    } else{
        $("body").removeClass('mini-navbar');
        SmoothlyMenu();

        if (localStorageSupport){
            localStorage.setItem("collapse_menu",'off');
        }
    }
});

// Enable/disable boxed layout
$('#boxedlayout').click(function (){
    if ($('#boxedlayout').is(':checked')){
        $("body").addClass('boxed-layout');
        $('#fixednavbar').prop('checked', false);
        $('#fixednavbar2').prop('checked', false);
        $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
        $("body").removeClass('fixed-nav');
        $("body").removeClass('fixed-nav-basic');
        $(".footer").removeClass('fixed');
        $('#fixedfooter').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixedfooter",'off');
        }


        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'on');
        }
    } else{
        $("body").removeClass('boxed-layout');

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }
    }
});

// Enable/disable fixed footer
$('#fixedfooter').click(function (){
    if ($('#fixedfooter').is(':checked')){
        $('#boxedlayout').prop('checked', false);
        $("body").removeClass('boxed-layout');
        $(".footer").addClass('fixed');

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixedfooter",'on');
        }
    } else{
        $(".footer").removeClass('fixed');

        if (localStorageSupport){
            localStorage.setItem("fixedfooter",'off');
        }
    }
});

// SKIN Select
$('.spin-icon').click(function (){
    $(".theme-config-box").toggleClass("show");
});

// Default skin
$('.s-skin-0').click(function (){
    $("body").removeClass("skin-1");
    $("body").removeClass("skin-2");
    $("body").removeClass("skin-3");
});

// Blue skin
$('.s-skin-1').click(function (){
    $("body").removeClass("skin-2");
    $("body").removeClass("skin-3");
    $("body").addClass("skin-1");
});

// Inspinia ultra skin
$('.s-skin-2').click(function (){
    $("body").removeClass("skin-1");
    $("body").removeClass("skin-3");
    $("body").addClass("skin-2");
});

// Yellow skin
$('.s-skin-3').click(function (){
    $("body").removeClass("skin-1");
    $("body").removeClass("skin-2");
    $("body").addClass("skin-3");
});

if (localStorageSupport){
    var collapse = localStorage.getItem("collapse_menu");
    var fixedsidebar = localStorage.getItem("fixedsidebar");
    var fixednavbar = localStorage.getItem("fixednavbar");
    var fixednavbar2 = localStorage.getItem("fixednavbar2");
    var boxedlayout = localStorage.getItem("boxedlayout");
    var fixedfooter = localStorage.getItem("fixedfooter");

    if (collapse == 'on'){
        $('#collapsemenu').prop('checked','checked')
    }
    if (fixedsidebar == 'on'){
        $('#fixedsidebar').prop('checked','checked')
    }
    if (fixednavbar == 'on'){
        $('#fixednavbar').prop('checked','checked')
    }
    if (fixednavbar2 == 'on'){
        $('#fixednavbar2').prop('checked','checked')
    }
    if (boxedlayout == 'on'){
        $('#boxedlayout').prop('checked','checked')
    }
    if (fixedfooter == 'on') {
        $('#fixedfooter').prop('checked','checked')
    }
}

</script>

<% end %>